### PR TITLE
Filter entries by category

### PR DESCRIPTION
**Pull request by Abban**
Howdy,

Small change to allow a category IDs to be passed to get_channel_entries(). It allows a single id or multiple separated by a pipe.

### CODE REVIEW

**Comment by putyourlightson** [comment]
nice addition but i'd like to get justin, the developer of the channel data library on board with this before merging the pull request and changing Channel_data_lib.php. that way we don't have multiple versions of the same library.

**Comment by StevenLangbroek** [comment]
Any update on this yet?

**Comment by Abban** [comment]
Ha!

**Comment by StevenLangbroek** [comment]
That was hilarious :D

**Comment by putyourlightson** [comment]
@Abban could you submit this as a pull request to the Channel Data library? i would like to have a single copy of the codebase and not modify Open API's version of it.
https://github.com/objectivehtml/Channel-Data

also this might help prompt justin to start more actively developing the Channel Data library again!!

thanks!

**Comment by Abban** [comment]
Yep I can, it might be best to just write a new model to handle it though?

Pretty sure I have code that will handle 80% of what the API lib needs already and it happens that I'm dry on paid work for the next couple of days so I _should_ be able to put something together. Let me take a look at what I have.

**Comment by neilbradley** [comment]
I would also be interested to see category data in get_channel_entries, but I would like to see the category groups and categories, with names and IDs in get_channel_entries - if that's possible? :)

Thanks.

**Pull request closed without merging**
